### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by Zalrakd** [HitomaruKonpaku/SadPanda#4]
Hello!

Unfortunately this doesn't seem to work properly.

I get the login screen, but when I enter my login details (and yes, I am registered in the forums) it says that no account exists with my username.

Again, I am registered to https://forums.e-hentai.org

Thanks for reading!

**Comment by HitomaruKonpaku** [comment]
Hi,

It's working on my side.

How old is your account?

Anyway, you can try to follow below steps

1. Go to https://forums.e-hentai.org/
2. Log in
3. Go to https://exhentai.org/
4. Press F12 to open dev tool, navigate to Application>Clear Storage>Clear site data
5. Reload

**Comment by Zalrakd** [comment]
Thanks for repying, tried to do what you suggested, but no luck.

The account was just registered today but seems to work fine on both https://forums.e-hentai.org and https://e-hentai.org, perhaps the issue is that it is too new?

**Comment by CodeZeke123** [comment]
Hi

My Account is now at something 9 month or so. Active rarely for sauce
purposes.

Clear Storage on Google Chrome is 0B  and If im going to refresh, still Sad
Panda came out of my screen. I never visit e-hentai or exhentai because of
complicated web design and sometimes filter goes to confusing when i want
so search something whatever i want. I am only visit the web for finding
something thats very rare to me to see it.

**Comment by HitomaruKonpaku** [comment]
@Zalrakd 

I think so.

New account can't access EH right away.

Try play https://hentaiverse.org/ for few days & go to EH again

**Comment by Zalrakd** [comment]
Thanks! 

Will update in 10 days
